@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvamFuYUB0ZXN0LmNvbSIsImV4cCI6MTc0NjM1OTEwMywidXNlcklEIjoxfQ.P0ViPG9wSVsVjnSN6Raow9zo_nQMBhsItiqEM8d7Rz8


### Get all events
GET http://localhost:8080/events 
Content-Type: application/json


### Create a new event
POST http://localhost:8080/events 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvamFuYUB0ZXN0LmNvbSIsImV4cCI6MTc0NjI3NjI5NywidXNlcklEIjoxfQ.o80KFGBm6tDN1pZ1bN2HyUryqBlV6K2a-LP1M4fffqw

{
  "name": "Predavanja  1",
  "description": "Predavanja 11",
  "date_time": "2025-05-03T11:00:00Z",
  "location": "Sala 2"
}


### Get event by id
GET http://localhost:8080/events/2
Content-Type: application/json

### Update an event
PUT http://localhost:8080/events/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuamljYUB0ZXN0LmNvbSIsImV4cCI6MTc0NjI3NTI4OSwidXNlcklEIjo0fQ.JIKHr85xfOijdoBhQusSckc9Q50hXscquXMzQAUoiCs

{
  "name": "Meditacija",
  "description": "Meditacija",
  "date_time": "2025-04-30T11:00:00Z",
  "location": "Sala 2"
}

### Delete an event
DELETE http://localhost:8080/events/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuamljYUB0ZXN0LmNvbSIsImV4cCI6MTc0NjI3NTI4OSwidXNlcklEIjo0fQ.JIKHr85xfOijdoBhQusSckc9Q50hXscquXMzQAUoiCs

### sign up user
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "bojana@test.com",
  "password": "test123"
}

### login user
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "bojana@test.com",
  "password": "test123"
}

### register for event
POST http://localhost:8080/events/6/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvamFuYUB0ZXN0LmNvbSIsImV4cCI6MTc0NjI3NjU2NCwidXNlcklEIjoxfQ.4pCMEEOpO8IDYY3hslWthQ1A77ehYlKLwoFwox731jY

### cancel registration
DELETE http://localhost:8080/events/6/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvamFuYUB0ZXN0LmNvbSIsImV4cCI6MTc0NjI3NjU2NCwidXNlcklEIjoxfQ.4pCMEEOpO8IDYY3hslWthQ1A77ehYlKLwoFwox731jY

### get registered users
GET http://localhost:8080/events/6/registered
Content-Type: application/json
Authorization: Bearer {{token}}