@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvamFuYUBiaXRjcmFmdC5pbmciLCJleHAiOjE3NDYzNTc1MTEsInN1YiI6MH0.hzwcxtReAyw7szxSPTPpABpjc4rPsMO1XtW9hFfqJvA


### get events
GET https://go-events.bitsandpieces.cloud/events

### get event by id
GET https://go-events.bitsandpieces.cloud/events/1

### create event
POST https://go-events.bitsandpieces.cloud/events
Authorization: Bearer {{token}}

{
  "name": "Popiti vode",
  "description": "Popiti vode",
  "date_time": "2025-05-04T11:00:00Z",
  "location": "Sala 1"
}

### Update event
PUT https://go-events.bitsandpieces.cloud/events/1

{
  "name": "Meditacija",
  "description": "Meditacija",
  "date_time": "2025-04-30T11:00:00Z",
  "location": "Sala 2"
}

### Delete event
DELETE https://go-events.bitsandpieces.cloud/events/1

### signup
POST https://go-events.bitsandpieces.cloud/signup

{
  "email": "bojana@bitcraft.ing",
  "password": "Sof1st1c1r4n!"
}

### login
POST https://go-events.bitsandpieces.cloud/login

{
  "email": "bojana@bitcraft.ing",
  "password": "Sof1st1c1r4n!"
}

### register for event
POST http://localhost:8080/events/6/register
Content-Type: application/json
Authorization: Bearer {{token}}